package Sistema;

import Formularios.Formulario02;
import Formularios.Formulario03;
import Formularios.Formulario04;

/**
 *
 * @author RAUL
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        registrodeClientes = new javax.swing.JMenuItem();
        resgistroPersonas = new javax.swing.JMenuItem();
        registroAnimales = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("MENU  DE REGISTRO");

        registrodeClientes.setMnemonic('o');
        registrodeClientes.setText("REGISTRO DE CLIENTES");
        registrodeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeClientesActionPerformed(evt);
            }
        });
        fileMenu.add(registrodeClientes);

        resgistroPersonas.setText("REGISTRO DE PERSONAS");
        resgistroPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resgistroPersonasActionPerformed(evt);
            }
        });
        fileMenu.add(resgistroPersonas);

        registroAnimales.setText("REGISTRO DE ANIMALES");
        registroAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAnimalesActionPerformed(evt);
            }
        });
        fileMenu.add(registroAnimales);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("MENU CITAS");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("REGISTRAR CITAS");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("REGISTRAR  DE FECHA DE VACUNACION");
        helpMenu.add(aboutMenuItem);

        jMenuItem3.setText("REGISTRAR HISTORIAL MEDICO /ENFERMEDADES");
        helpMenu.add(jMenuItem3);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void registrodeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeClientesActionPerformed
        Formulario02 a = new Formulario02();
        escritorio.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_registrodeClientesActionPerformed

    private void resgistroPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgistroPersonasActionPerformed
        Formulario03 a = new Formulario03();
        escritorio.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_resgistroPersonasActionPerformed

    private void registroAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAnimalesActionPerformed
        Formulario04 a = new Formulario04();
        escritorio.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_registroAnimalesActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registroAnimales;
    private javax.swing.JMenuItem registrodeClientes;
    private javax.swing.JMenuItem resgistroPersonas;
    // End of variables declaration//GEN-END:variables

}
